# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fhpopular-repos-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://fhpopularreposregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_524d9f834542400ea310dc2ba9ac95c9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_79fa5a42f6d54265a2879ce34716a54d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: fhpopularreposregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_524d9f834542400ea310dc2ba9ac95c9 }}/fhpopular-repos:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fhpopular-repos-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8885754f146f4153952b808c674defef }}
        images: 'fhpopularreposregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_524d9f834542400ea310dc2ba9ac95c9 }}/fhpopular-repos:${{ github.sha }}'